### ISSUE TITLE
Getting this error while running

### ISSUE THREAD

**Issue by d3vilsn0w** [CrazyPython/svgmanip#5]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-84f6d6a45fa1> in <module>
      2 output = Element(384, 356)  # size of the output file.
      3 
----> 4 fate = Element('assets/bn1.svg').rotate(-15)
      5 skip = Element('assets/skip.svg').rotate(-5)
      6 attack = Element('assets/attack.svg').rotate(5)

~/opt/anaconda3/lib/python3.8/site-packages/svgmanip/_generator.py in __init__(self, width_or_filename, height, *svgelements)
     80             assert len(svgelements) == 0
     81             svgfigure = svgutils.transform.fromfile(width_or_filename)
---> 82             svg = SVG(width_or_filename).scale(1)  # scale of 1 converts to an Element
     83             super(Element, self).__init__(self._parse_string_dimension(svgfigure.width),
     84                                           self._parse_string_dimension(svgfigure.height), svg)

~/opt/anaconda3/lib/python3.8/site-packages/svgutils/compose.py in __init__(self, fname, fix_mpl)
    120 
    121             # if height/width is in % units, we can't store the absolute values
--> 122             if svg.width.endswith("%"):
    123                 self._width = None
    124             else:

AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by CrazyPython** [comment]
The svg file is not present on your computer. Please change "assets/bn1.svg" to the path of a SVG file that is present on your computer.
